#!/bin/bash
# Used to define paths for coin daemons
#
# @author webworker01
#

komodolike=('VRSC' 'HUSH3' 'MCL')

#declare non komodo clis - set the full path accessible as the second part of each string, the 3rd entry is the name of the data dir for the coin and assumes they are in $HOME
hushcli="$HOME/hush3/src/komodo-cli -ac_name=HUSH3"
hushd="$HOME/hush3/src/hushd"
verusd="$HOME/VerusCoin/src/verusd -pid=${HOME}/.komodo/VRSC/komodod.pid"
#marmaracli="$HOME/Marmara-v.1.0/src/komodo-cli -ac_name=MCL"
#marmarad="$HOME/Marmara-v.1.0/src/komodod -ac_name=MCL -ac_supply=2000000 -ac_cc=2 -addnode=37.148.210.158 -addnode=37.148.212.36 -addressindex=1 -spentindex=1 -ac_marmara=1 -ac_staked=75 -ac_reward=3000000000 -pid=${HOME}/.komodo/HUSH3/komodod.pid"

coinsfirst=(
    'BTC $HOME/bitcoin/src/bitcoin-cli $HOME/bitcoin/src/bitcoind .bitcoin rescan bitcoind.pid'
    #'VRSC $HOME/VerusCoin/src/verus $verusd .komodo/VRSC zimport komodod.pid'
    #'DPOW $dpowcli $dpowd .komodo/DPOW kmd komodod.pid'
)

coinsthird=(
    'CHIPS $HOME/chips3/src/chips-cli $HOME/chips3/src/chipsd .chips rescan chipsd.pid'
    #'GAME $HOME/GameCredits/src/gamecredits-cli $HOME/GameCredits/src/gamecreditsd .gamecredits newaddress gamecredits.pid'
    'EMC2 $HOME/einsteinium/src/einsteinium-cli $HOME/einsteinium/src/einsteiniumd .einsteinium newaddress einsteinium.pid'
    #'GIN $HOME/gincoin-core/src/gincoin-cli $HOME/gincoin-core/src/gincoind .gincoincore newaddress gincoind.pid'
    'HUSH3 $hushcli $hushd .komodo/HUSH3 kmd komodod.pid'
    'VRSC $HOME/VerusCoin/src/verus $verusd .komodo/VRSC zimport komodod.pid'
    'AYA $HOME/AYAv2/src/aryacoin-cli $HOME/AYAv2/src/aryacoind .aryacoin newaddress aryacoin.pid'
    #'MCL $marmaracli $marmarad .komodo/MCL kmd komodod.pid'
)

#for git checking - path and remote branch
declare -A repos=(
    [KMD]="$HOME/komodo origin/master"
    [dPoW]="$HOME/dPoW origin/master"
    # [CHIPS]="$HOME/chips3 origin/dev"
    # [GAME]="$HOME/GameCredits origin/master"
    # [EMC2]="$HOME/einsteinium origin/master"
    # [GIN]="$HOME/gincoin-core origin/master"
    # [VRSC]="$HOME/VerusCoin origin/master"
)
